### ISSUE TITLE
100% Memory usage crash during MIMIC-IV preprocessing

### ISSUE THREAD

**Issue by JosephSBoyle** [JoakimEdin/medical-coding-reproducibility#2]
Hi thank you for open-sourcing your project.

I'm trying to run the MIMIC-IV preprocessing `python prepare_data/prepare_mimiciv.py` (step 5 of the Prepare MIMIC-IV section in README.md) but after 2+ hours it seems to crashing and infinitely spawning new processes and consuming 100% of my machine's RAM.

Unfortunately I was not able to capture the stack as I had to power off my machine as it had crashed; but the errors seemed to be related to `vaex` and multi-processing related. I have tried this twice now, each time cloning the repo from scratch with the same outcome.

If it helps I am on windows 10 running python 3.10 with 32GB RAM and a 16 core CPU.

**Comment by JoakimEdin** [comment]
I’m on vacation! I’m back on Tuesday and will have a look at it

**Comment by JoakimEdin** [comment]
Can you send me the error you got?

**Comment by JosephSBoyle** [comment]
```
INFO:root:Loading data from discharge.csv.gz into a pandas dataframe. This may take a while...
INFO:root:Loading data from procedures_icd.csv.gz into a pandas dataframe. This may take a while...
INFO:root:Loading data from diagnoses_icd.csv.gz into a pandas dataframe. This may take a while...
INFO:root:discharge.feather already exists, loading data from discharge.feather into a pandas dataframe.
INFO:root:discharge.feather already exists, loading data from discharge.feather into a pandas dataframe.
INFO:root:discharge.feather already exists, loading data from discharge.feather into a pandas dataframe.
INFO:root:discharge.feather already exists, loading data from discharge.feather into a pandas dataframe.
INFO:root:discharge.feather already exists, loading data from discharge.feather into a pandas dataframe.
INFO:root:discharge.feather already exists, loading data from discharge.feather into a pandas dataframe.
INFO:root:discharge.feather already exists, loading data from discharge.feather into a pandas dataframe.
INFO:root:discharge.feather already exists, loading data from discharge.feather into a pandas dataframe.
INFO:root:discharge.feather already exists, loading data from discharge.feather into a pandas dataframe.
INFO:root:discharge.feather already exists, loading data from discharge.feather into a pandas dataframe.
INFO:root:discharge.feather already exists, loading data from discharge.feather into a pandas dataframe.
INFO:root:discharge.feather already exists, loading data from discharge.feather into a pandas dataframe.
INFO:root:discharge.feather already exists, loading data from discharge.feather into a pandas dataframe.
INFO:root:discharge.feather already exists, loading data from discharge.feather into a pandas dataframe.
INFO:root:discharge.feather already exists, loading data from discharge.feather into a pandas dataframe.
INFO:root:discharge.feather already exists, loading data from discharge.feather into a pandas dataframe.
INFO:root:procedures_icd.feather already exists, loading data from procedures_icd.feather into a pandas dataframe.
INFO:root:procedures_icd.feather already exists, loading data from procedures_icd.feather into a pandas dataframe.
INFO:root:diagnoses_icd.feather already exists, loading data from diagnoses_icd.feather into a pandas dataframe.
INFO:root:diagnoses_icd.feather already exists, loading data from diagnoses_icd.feather into a pandas dataframe.
INFO:root:procedures_icd.feather already exists, loading data from procedures_icd.feather into a pandas dataframe.
INFO:root:diagnoses_icd.feather already exists, loading data from diagnoses_icd.feather into a pandas dataframe.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Program Files\Python310\lib\runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Program Files\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Joe\Desktop\medical-coding-reproducibility\prepare_data\prepare_mimiciv.py", line 107, in <module>
    mimic_notes = load_gz_file_into_df(download_dir_note / "note/discharge.csv.gz")
  File "c:\users\joe\desktop\medical-coding-reproducibility\prepare_data\utils.py", line 46, in load_gz_file_into_df
    return pd.read_feather(download_dir / f"{stemmed_filename}.feather")
  File "C:\Users\Joe\AppData\Roaming\Python\Python310\site-packages\pandas\io\feather_format.py", line 132, in read_feather
    return feather.read_feather(
  File "C:\Users\Joe\AppData\Roaming\Python\Python310\site-packages\pyarrow\feather.py", line 226, in read_feather
    return (read_table(
  File "pyarrow\array.pxi", line 830, in pyarrow.lib._PandasConvertible.to_pandas
  File "pyarrow\table.pxi", line 3990, in pyarrow.lib.Table._to_pandas
  File "C:\Users\Joe\AppData\Roaming\Python\Python310\site-packages\pyarrow\pandas_compat.py", line 820, in table_to_blockmanager
    blocks = _table_to_blocks(options, table, categories, ext_columns_dtypes)
  File "C:\Users\Joe\AppData\Roaming\Python\Python310\site-packages\pyarrow\pandas_compat.py", line 1169, in _table_to_blocks
    result = pa.lib.table_to_blocks(options, block_table, categories,
  File "pyarrow\table.pxi", line 2646, in pyarrow.lib.table_to_blocks
  File "pyarrow\error.pxi", line 138, in pyarrow.lib.check_status
pyarrow.lib.ArrowException: Unknown error: Wrapping  
```

The error is continously repeated in between what seems to be different discharge notes.

**Comment by JoakimEdin** [comment]
The error you sent here is different from what you described earlier. This is an error for when pd.read_feather. Can you try running it this code in the same conda environment?

import pandas as pd

x= pd.DataFrame({“a”: [1,2], “b”:[“1”,“2”]})
x.to_feather(“test.feather”)
y = pd.read_feather(“test.feather”)
print(y)

**Comment by JoakimEdin** [comment]
It seems like the error is caused by the code being run by multiple threads. The code should not print “INFO:root:discharge.feather already exists, loading data from discharge.feather into a pandas dataframe.” multiple times. The code doesn’t implement any multi threading or multi processing outside the vaex, so the issue must lie in how the code is run. Can you try to reinstall your python package and conda environment?

**Comment by JoakimEdin** [comment]
I think it is related to the other issue you reported and I fixed. Just git pull, reinstall the conda environment and try again!

**Comment by JoakimEdin** [comment]
Did it work @JosephSBoyle?

**Comment by JosephSBoyle** [comment]
Hi Joakim, apologies in the delay in getting back to you, this slipped my TODO list.

I did a fresh git clone + followed the installation steps but it seems that the same error is occuring when preparing the MIMIC IV data:

```
...
INFO:root:discharge.feather already exists, loading data from discharge.feather into a pandas dataframe.
INFO:root:procedures_icd.feather already exists, loading data from procedures_icd.feather into a pandas dataframe.
INFO:root:diagnoses_icd.feather already exists, loading data from diagnoses_icd.feather into a pandas dataframe.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Joe\.conda\envs\coding\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Joe\.conda\envs\coding\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Joe\.conda\envs\coding\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Joe\.conda\envs\coding\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Joe\.conda\envs\coding\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Joe\.conda\envs\coding\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Joe\.conda\envs\coding\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Joe\Desktop\medical-coding-reproducibility\prepare_data\prepare_mimiciv.py", line 107, in <module>
    mimic_notes = load_gz_file_into_df(download_dir_note / "note/discharge.csv.gz")
  File "c:\users\joe\desktop\medical-coding-reproducibility\prepare_data\utils.py", line 46, in load_gz_file_into_df
    return pd.read_feather(download_dir / f"{stemmed_filename}.feather")
  File "C:\Users\Joe\AppData\Roaming\Python\Python310\site-packages\pandas\io\feather_format.py", line 132, in read_feather
    return feather.read_feather(
  File "C:\Users\Joe\AppData\Roaming\Python\Python310\site-packages\pyarrow\feather.py", line 226, in read_feather
    return (read_table(
  File "pyarrow\array.pxi", line 830, in pyarrow.lib._PandasConvertible.to_pandas
  File "pyarrow\table.pxi", line 3990, in pyarrow.lib.Table._to_pandas
  File "C:\Users\Joe\AppData\Roaming\Python\Python310\site-packages\pyarrow\pandas_compat.py", line 820, in table_to_blockmanager
    blocks = _table_to_blocks(options, table, categories, ext_columns_dtypes)
  File "C:\Users\Joe\AppData\Roaming\Python\Python310\site-packages\pyarrow\pandas_compat.py", line 1169, in _table_to_blocks
    result = pa.lib.table_to_blocks(options, block_table, categories,
  File "pyarrow\table.pxi", line 2646, in pyarrow.lib.table_to_blocks
  File "pyarrow\error.pxi", line 117, in pyarrow.lib.check_status
pyarrow.lib.ArrowMemoryError: malloc of size 67108864 failed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Joe\.conda\envs\coding\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Joe\.conda\envs\coding\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Joe\.conda\envs\coding\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Joe\.conda\envs\coding\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Joe\.conda\envs\coding\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Joe\.conda\envs\coding\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Joe\.conda\envs\coding\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Joe\Desktop\medical-coding-reproducibility\prepare_data\prepare_mimiciv.py", line 107, in <module>
    mimic_notes = load_gz_file_into_df(download_dir_note / "note/discharge.csv.gz")
  File "c:\users\joe\desktop\medical-coding-reproducibility\prepare_data\utils.py", line 46, in load_gz_file_into_df
    return pd.read_feather(download_dir / f"{stemmed_filename}.feather")
  File "C:\Users\Joe\AppData\Roaming\Python\Python310\site-packages\pandas\io\feather_format.py", line 132, in read_feather
    return feather.read_feather(
  File "C:\Users\Joe\AppData\Roaming\Python\Python310\site-packages\pyarrow\feather.py", line 226, in read_feather
    return (read_table(
  File "pyarrow\array.pxi", line 830, in pyarrow.lib._PandasConvertible.to_pandas
  File "pyarrow\table.pxi", line 3990, in pyarrow.lib.Table._to_pandas
  File "C:\Users\Joe\AppData\Roaming\Python\Python310\site-packages\pyarrow\pandas_compat.py", line 820, in table_to_blockmanager
    blocks = _table_to_blocks(options, table, categories, ext_columns_dtypes)
  File "C:\Users\Joe\AppData\Roaming\Python\Python310\site-packages\pyarrow\pandas_compat.py", line 1169, in _table_to_blocks
    result = pa.lib.table_to_blocks(options, block_table, categories,
  File "pyarrow\table.pxi", line 2646, in pyarrow.lib.table_to_blocks
  File "pyarrow\error.pxi", line 138, in pyarrow.lib.check_status
pyarrow.lib.ArrowException: Unknown error: Wrapping
```

Seeing `pyarrow.lib.ArrowMemoryError: malloc of size 67108864 failed` and observing that memory use was 99% I would hazard a guess that it's an OOM error.

**Comment by JoakimEdin** [comment]
It seems like you don’t have enough RAM on your computer to fit the whole dataset 😢
