### ISSUE TITLE
huggingface_hub.utils._validators.HFValidationError

### ISSUE THREAD

**Issue by 4rshdeep** [JoakimEdin/medical-coding-reproducibility#3]
I am trying to run `PYTHONPATH=. python main.py experiment=mimiciv_icd10/plm_icd gpu=0` but I get the following error

```
  File "/opt/conda/envs/coding/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/opt/conda/envs/coding/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/opt/conda/envs/coding/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/opt/conda/envs/coding/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/abc/medical-coding-reproducibility/main.py", line 76, in main
    text_transform = get_transform(
  File "/home/abc/medical-coding-reproducibility/src/factories.py", line 108, in get_transform
    transform_class = getattr(transform, config.name)(**config.configs)
  File "/home/abc/medical-coding-reproducibility/src/data/transform.py", line 234, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(model_path, **kwargs)
  File "/opt/conda/envs/coding/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 598, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/opt/conda/envs/coding/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 442, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/opt/conda/envs/coding/lib/python3.10/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/opt/conda/envs/coding/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    validate_repo_id(arg_value)
  File "/opt/conda/envs/coding/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 166, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '<path/to/RoBERTa-base-PM-M3-Voc-hf>'. Use `repo_type` argument if needed.
```

My hunch is that there must be a problem with my config file, which looks like

```
(coding) abc@embeddings:~/medical-coding-reproducibility$ ls RoBERTa-base-PM-M3-Voc/RoBERTa-base-PM-M3-Voc-hf/
config.json  merges.txt  pytorch_model.bin  vocab.json
(coding) abc@embeddings:~/medical-coding-reproducibility$ cat configs/model/plm_icd.yaml
name: PLMICD
configs:
  model_path: /home/abc/medical-coding-reproducibility/RoBERTa-base-PM-M3-Voc/RoBERTa-base-PM-M3-Voc-hf

```

Any idea what is wrong here?

**Comment by JoakimEdin** [comment]
Hmmm, I think your config file looks correct.

This is my config file

```
name: PLMICD
configs:
  model_path: /data/je/pretrained_models/RoBERTa-base-PM-M3-Voc-hf
```

and this is what the folder contains:
`ls /data/je/pretrained_models/RoBERTa-base-PM-M3-Voc-hf`
`config.json  merges.txt  pytorch_model.bin  vocab.json`

I have two theories of what goes wrong for you:

1. You are providing the wrong path. Maybe what you posted `ls RoBERTa-base-PM-M3-Voc/RoBERTa-base-PM-M3-Voc-hf/` is slightly different from the path in the config file. Validate with `ls /home/abc/medical-coding-reproducibility/RoBERTa-base-PM-M3-Voc/RoBERTa-base-PM-M3-Voc-hf`.
2. Maybe hugging face is confused by two folders named RoBERTa-base-PM-M3-Voc. Try changing the name of the parent folder.

Hope you find a solution. Sorry, I couldn't help more!

**Comment by JoakimEdin** [comment]
Did you figure it out @4rshdeep?

**Comment by 4rshdeep** [comment]
No - am I doing anything wrong?

**Comment by 4rshdeep** [comment]
Hey - @JoakimEdin, still getting the same error 🤔 
```
(coding) abc@embeddings:~/medical-coding-reproducibility$ ls pretrained_model/RoBERTa-base-PM-M3-Voc-hf/
config.json  merges.txt  pytorch_model.bin  vocab.json
(coding) abc@embeddings:~/medical-coding-reproducibility$ PYTHONPATH=. python main.py experiment=mimiciv_icd10/plm_icd gpu=0

[2023-08-27 08:57:40,365][infotropy.utils.random][INFO] - Set 'numpy', 'random' and 'torch' random seed to 1337
'Device: cuda'
'CUDA_VISIBLE_DEVICES: 0'
Error executing job with overrides: ['experiment=mimiciv_icd10/plm_icd', 'gpu=0']
Traceback (most recent call last):
  File "/home/abc/medical-coding-reproducibility/main.py", line 76, in main
    text_transform = get_transform(
  File "/home/abc/medical-coding-reproducibility/src/factories.py", line 108, in get_transform
    transform_class = getattr(transform, config.name)(**config.configs)
  File "/home/abc/medical-coding-reproducibility/src/data/transform.py", line 234, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(model_path, **kwargs)
  File "/opt/conda/envs/coding/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 598, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/opt/conda/envs/coding/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 442, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/opt/conda/envs/coding/lib/python3.10/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/opt/conda/envs/coding/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    validate_repo_id(arg_value)
  File "/opt/conda/envs/coding/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 166, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '<path/to/RoBERTa-base-PM-M3-Voc-hf>'. Use `repo_type` argument if needed.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by JoakimEdin** [comment]
Try to make a new script to speed up the debugging. Try to run this:

```python
from transformers import RobertaModel, AutoConfig

model_path = "path/to/your/model"
num_classes=1000


config = AutoConfig.from_pretrained(
            model_path, num_labels=num_classes, finetuning_task=None
        )

roberta = RobertaModel(
            config, add_pooling_layer=False
        ).from_pretrained(model_path, config=config)
```

**Comment by 4rshdeep** [comment]
This runs - script still doesn't

**Comment by 4rshdeep** [comment]
I tried to go deeper at the error source. Do you think `cfg.text_transform` is correct?
`
{'name': 'HuggingFaceTokenizer', 'configs': {'model_path': '<path/to/RoBERTa-base-PM-M3-Voc-hf>', 'add_special_token': True, 'padding': False, 'use_fast': True, 'do_lower_case': True, 'max_length': None, 'truncation': False}}
`
<img width="1440" alt="image" src="https://github.com/JoakimEdin/medical-coding-reproducibility/assets/23432952/99b40659-8558-4da6-bf3f-7d22f86b6b11">

**Comment by 4rshdeep** [comment]
Not covered in Readme but I also needed to update this - https://github.com/JoakimEdin/medical-coding-reproducibility/blob/main/configs/text_transform/huggingface.yaml#L3

**Comment by 4rshdeep** [comment]
Still didn't run - I had to debug further, got it to run after removing wandb callback.

**Comment by AHMAD-DOMA** [comment]
> 

Could you please explain more about how you removed the wandb callback ?.

**Comment by JoakimEdin** [comment]
Aaah makes sense! I indeed forgot about the tokenizer config. Will update the readme tomorrow. Thank you so much!

So it works now?

**Comment by JoakimEdin** [comment]
I have added info about the tokenizer config file in the README.md! Let me know if you think it will solve the issue for others and I will close this issue 😊.

**Comment by JoakimEdin** [comment]
I assume the issue has been resolved.
