### ISSUE TITLE
huggingface_hub.utils._validators.HFValidationError while evaluating the mimiciii_clean/plm_icd model.

### ISSUE THREAD

**Issue by Ahmed-Mortadi** [JoakimEdin/medical-coding-reproducibility#5]
## Description
I am attempting to evaluate the "mimiciii_clean/plm_icd" model on the "mimiciii_clean" dataset following these steps:

1. **Dataset Preparation:** I prepared the dataset by running the "prepare_data/prepare_mimiciii_clean.py" script on the 'mimiciii' directory.

2. **Checkpoint Download:** I downloaded the necessary checkpoints from the link provided in the README.md file. Here's a screenshot confirming the presence of these checkpoints for the "plm_icd" model:
   ![Checkpoint Screenshot](https://github.com/JoakimEdin/medical-coding-reproducibility/assets/52766027/dfc7184e-e45a-4c08-8bc8-29097c56be2c)

3. **Execution Command:** I executed the following command:
   ```shell
   python main.py experiment=mimiciii_clean/plm_icd gpu=0 load_model=/content/files/model_checkpoints/mimiciii_clean/plm-icd +epochs=0 callbacks=no_wandb

## Error Encountered

After running the command, I encountered the following error:

```shell
[2023-08-31 05:28:20,075][infotropy.utils.random][INFO] - Set 'numpy', 'random' and 'torch' random seed to 1337
'Device: cuda'
'CUDA_VISIBLE_DEVICES: 0'
loaded transform
Error executing job with overrides: ['experiment=mimiciii_clean/plm_icd', 'gpu=0', 'load_model=/content/files/model_checkpoints/mimiciii_clean/plm-icd', '+epochs=0', 'callbacks=no_wandb']
Traceback (most recent call last):
  File "/content/main.py", line 150, in <module>
    main()  # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.10/dist-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/usr/local/lib/python3.10/dist-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/usr/local/lib/python3.10/dist-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/content/main.py", line 76, in main
    text_transform = get_transform(
  File "/content/src/factories.py", line 108, in get_transform
    transform_class = getattr(transform, config.name)(**config.configs)
  File "/content/src/data/transform.py", line 234, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(model_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/tokenization_auto.py", line 677, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/tokenization_auto.py", line 510, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 428, in cached_file
    resolved_file = hf_hub_download(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '<path/to/RoBERTa-base-PM-M3-Voc-hf>'. Use `repo_type` argument if needed.
```

Could someone please verify the correctness of my steps and provide guidance on resolving this error? Your assistance would be greatly appreciated.

**Comment by JoakimEdin** [comment]
I think it is related to this issue: https://github.com/JoakimEdin/medical-coding-reproducibility/issues/3#issue-1854992856

I forgot to mention that you have to change the model_path in the model and tokenizer config file. I will update the readme today!

**Comment by JoakimEdin** [comment]
I have now added the info to the README.md!

**Comment by sumeromer** [comment]
> I have now added the info to the README.md!

Thanks, Joakim. Great work that made so much easier and reproducible all the studies that you reported! 

Yesterday I trained one by one all models on MIMIC-IV/ICD-10 except for PLM-ICM. Then, additionally writing ```model_path```to ```configs/text_transform/huggingface.yaml``` resolved the issue in PLM-ICD.

**Comment by JoakimEdin** [comment]
Great news! Thank you for reporting your issues! I will close this issue now. 😊

**Comment by Ahmed-Mortadi** [comment]
Sorry to bother you, Joakim ..

I am trying to just evaluate the PLM-ICD model, not train it from scratch, and after updating the path of the model_path in the model and tokenizer config file, the error disappeared but a new error appeared.

My command:

```shell
python main.py experiment=mimiciii_clean/plm_icd gpu=0 load_model=/content/files/model_checkpoints/mimiciii_clean/plm-icd trainer.epochs=0 callbacks=no_wandb
```
The output (containing the error):
```shell
[2023-08-31 22:18:46,749][infotropy.utils.random][INFO] - Set 'numpy', 'random' and 'torch' random seed to 1337
'Device: cuda'
'CUDA_VISIBLE_DEVICES: 0'
loaded transform
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
loaded transform
Transforming text... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:01:01
{
│   'num_classes': 3681,
│   'num_examples': 52712,
│   'num_train_tokens': 58147709,
│   'average_tokens_per_example': 1513.5050652602822,
│   'num_train_examples': 38401,
│   'num_val_examples': 5577,
│   'num_test_examples': 8734,
│   'num_train_classes': 3681,
│   'num_val_classes': 3676,
│   'num_test_classes': 3681,
│   'average_classes_per_example': 15.584838366975262,
│   'vocab_size': 50001,
│   'pad_index': 0
}
Creating examples ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:02
Creating examples ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Creating examples ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
'Train batch size: 1'
WARNING: drop_last=True, dropping last non batch-size batch in every bucket ... 
2023-08-31 22:20:23.897516: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
'Accumulating gradients over 16 batch(es).'
Error executing job with overrides: ['experiment=mimiciii_clean/plm_icd', 'gpu=0', 'load_model=/content/files/model_checkpoints/mimiciii_clean/plm-icd', 'trainer.epochs=0', 'callbacks=no_wandb']
Traceback (most recent call last):
  File "/content/main.py", line 150, in <module>
    main()  # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.10/dist-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/usr/local/lib/python3.10/dist-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/usr/local/lib/python3.10/dist-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/content/main.py", line 146, in main
    trainer.fit()
  File "/content/src/trainer/trainer.py", line 76, in fit
    self.on_fit_end()
  File "/content/src/trainer/trainer.py", line 233, in on_fit_end
    callback.on_fit_end(self)
  File "/content/src/trainer/callbacks.py", line 152, in on_fit_end
    trainer.load_checkpoint("best_model.pt")
  File "/content/src/trainer/trainer.py", line 360, in load_checkpoint
    checkpoint = torch.load(self.experiment_path / file_name)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/content/files/model_checkpoints/mimiciii_clean/plm-icd/best_model.pt'
```
